timeSync: Portable way to print 64bit time_t
This ensures when 64bit time_t is used on 32bit architectures (
-D_TIME_BITS=64 ) then it can print it correctly as well.

Fixes
pllLinux.c:43:20: error: format specifies type 'long' but the argument has type 'long long' [-Werror,-Wformat]
|            prefix, tx->offset, tx->freq, tx->maxerror, tx->esterror,
|                    ^~~~~~~~~~

Signed-off-by: Khem Raj <raj.khem@gmail.com>