Fix build failures about json-c's debug.h
open-vm-tools currently fails to build on certain system setup due to conflicting header filename (debug.h). The errors look like:

```
copyPasteUIX11.h: In member function 'void CopyPasteUIX11::SetBlockControl(DnDBlockControl*)':                                                                                                                                                                                     
copyPasteUIX11.h:90:9: error: 'Debug' was not declared in this scope; did you mean 'g_debug'?                                                                                                                                                                                      
   90 |       { Debug("Setting mBlockCtrl to %p\n", blockCtrl);                                                                                                                                                                                                                    
      |         ^~~~~                                                                                                                                                                                                                                                              
      |         g_debug                                        
```

This is because when util-linux's configured with cryptsetup support, a dependency chain brings in json-c's include path into GTK_CPPFLAGS and there's `/usr/include/json-c/debug.h` with the same filename.

```
gdk-pixbuf-xlib-2.0 -> gdk-pixbuf-2.0 -> gio-2.0 -> mount -> libcryptsetup -> json-c
```

Preferring our include path over GTK_CPPFLAGS fixes building here.